import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Nav } from "@/components/site/nav";
import { clerkEnabled } from "@/lib/auth";
import { Footer } from "@/components/site/footer";
import { Section, SectionHead, FinalCta } from "@/components/site/sections";
import { Reveal } from "@/components/site/reveal";
import { Card, Pill, Button } from "@/components/ui";
import { EXAMPLES } from "@/lib/examples";

export const metadata: Metadata = {
  title: "Examples",
  description:
    "Real packs generated by DINOL. See the titles, thumbnails, hooks, debate kits and virality scores before you type anything.",
};

export default function ExamplesPage() {
  return (
    <>
      <Nav authEnabled={clerkEnabled} />
      <main>
        <Section>
          <Reveal>
            <SectionHead
              eyebrow="Examples"
              title={<>Real output, <span className="hl">nothing staged</span></>}
              sub="These packs came out of the live product. Open one, read the whole thing, then decide."
            />
          </Reveal>

          <div className="mt-14 grid gap-5 md:grid-cols-3">
            {EXAMPLES.map((e, i) => (
              <Reveal key={e.slug} delay={i * 0.07}>
                <Link href={`/p/${e.slug}`} className="group block h-full">
                  <Card className="flex h-full flex-col p-6 transition-all duration-300 group-hover:-translate-y-1 group-hover:shadow-lift">
                    <div className="flex items-center gap-2">
                      <Pill className="capitalize">{e.mode}</Pill>
                      <Pill className="capitalize">{e.tone}</Pill>
                    </div>
                    <h3 className="display mt-4 text-[22px] leading-tight">
                      {e.label}
                    </h3>
                    <p className="mt-3 flex-1 text-[14px] leading-relaxed text-[var(--espresso-soft)]">
                      {e.summary}
                    </p>
                    <div className="mt-5 flex items-center justify-between border-t border-[var(--line)] pt-4">
                      <div>
                        <div className="display text-[26px] text-[var(--espresso)]">
                          {e.score?.overall ?? "--"}
                        </div>
                        <div className="text-[11px] text-[var(--muted)]">
                          Virality score
                        </div>
                      </div>
                      <span className="flex items-center gap-1.5 text-[13px] font-semibold text-[var(--orange)]">
                        Open pack <ArrowRight className="size-3.5" />
                      </span>
                    </div>
                  </Card>
                </Link>
              </Reveal>
            ))}
          </div>

          <Reveal delay={0.2}>
            <div className="mt-12 text-center">
              <Link href="/app">
                <Button size="lg">
                  Generate your own <ArrowRight className="size-4" />
                </Button>
              </Link>
            </div>
          </Reveal>
        </Section>
        <FinalCta />
      </main>
      <Footer />
    </>
  );
}
